name: Clean Up Branches

on:
  schedule:
    - cron: "0 0 * * 0"  # Cada domingo a medianoche
  workflow_dispatch:  # Allows manual triggering

jobs:
  cleanup:
    uses: ETrigosNivelics/shared-workflows/.github/workflows/cleanup_branches.yml@main
    with:
      dryRun: true
      months: 5

